// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: proto/stat/stat.proto

package stat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DockerStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Images       *DockerStat_Item `protobuf:"bytes,1,opt,name=images,proto3" json:"images,omitempty"`
	Containers   *DockerStat_Item `protobuf:"bytes,2,opt,name=containers,proto3" json:"containers,omitempty"`
	LocalVolumes *DockerStat_Item `protobuf:"bytes,3,opt,name=local_volumes,json=localVolumes,proto3" json:"local_volumes,omitempty"`
	BuildCache   *DockerStat_Item `protobuf:"bytes,4,opt,name=build_cache,json=buildCache,proto3" json:"build_cache,omitempty"`
}

func (x *DockerStat) Reset() {
	*x = DockerStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stat_stat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DockerStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerStat) ProtoMessage() {}

func (x *DockerStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stat_stat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerStat.ProtoReflect.Descriptor instead.
func (*DockerStat) Descriptor() ([]byte, []int) {
	return file_proto_stat_stat_proto_rawDescGZIP(), []int{0}
}

func (x *DockerStat) GetImages() *DockerStat_Item {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *DockerStat) GetContainers() *DockerStat_Item {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *DockerStat) GetLocalVolumes() *DockerStat_Item {
	if x != nil {
		return x.LocalVolumes
	}
	return nil
}

func (x *DockerStat) GetBuildCache() *DockerStat_Item {
	if x != nil {
		return x.BuildCache
	}
	return nil
}

type GetDockerStatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDockerStatRequest) Reset() {
	*x = GetDockerStatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stat_stat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDockerStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDockerStatRequest) ProtoMessage() {}

func (x *GetDockerStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stat_stat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDockerStatRequest.ProtoReflect.Descriptor instead.
func (*GetDockerStatRequest) Descriptor() ([]byte, []int) {
	return file_proto_stat_stat_proto_rawDescGZIP(), []int{1}
}

type GetDockerStatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DockerStat *DockerStat `protobuf:"bytes,1,opt,name=docker_stat,json=dockerStat,proto3" json:"docker_stat,omitempty"`
}

func (x *GetDockerStatResponse) Reset() {
	*x = GetDockerStatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stat_stat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDockerStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDockerStatResponse) ProtoMessage() {}

func (x *GetDockerStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stat_stat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDockerStatResponse.ProtoReflect.Descriptor instead.
func (*GetDockerStatResponse) Descriptor() ([]byte, []int) {
	return file_proto_stat_stat_proto_rawDescGZIP(), []int{2}
}

func (x *GetDockerStatResponse) GetDockerStat() *DockerStat {
	if x != nil {
		return x.DockerStat
	}
	return nil
}

type FsStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Free  uint64 `protobuf:"varint,2,opt,name=free,proto3" json:"free,omitempty"`
	Used  uint64 `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
}

func (x *FsStat) Reset() {
	*x = FsStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stat_stat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsStat) ProtoMessage() {}

func (x *FsStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stat_stat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsStat.ProtoReflect.Descriptor instead.
func (*FsStat) Descriptor() ([]byte, []int) {
	return file_proto_stat_stat_proto_rawDescGZIP(), []int{3}
}

func (x *FsStat) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *FsStat) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *FsStat) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

type GetFsStatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFsStatRequest) Reset() {
	*x = GetFsStatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stat_stat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFsStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFsStatRequest) ProtoMessage() {}

func (x *GetFsStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stat_stat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFsStatRequest.ProtoReflect.Descriptor instead.
func (*GetFsStatRequest) Descriptor() ([]byte, []int) {
	return file_proto_stat_stat_proto_rawDescGZIP(), []int{4}
}

type GetFsStatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FsStat *FsStat `protobuf:"bytes,1,opt,name=fs_stat,json=fsStat,proto3" json:"fs_stat,omitempty"`
}

func (x *GetFsStatResponse) Reset() {
	*x = GetFsStatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stat_stat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFsStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFsStatResponse) ProtoMessage() {}

func (x *GetFsStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stat_stat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFsStatResponse.ProtoReflect.Descriptor instead.
func (*GetFsStatResponse) Descriptor() ([]byte, []int) {
	return file_proto_stat_stat_proto_rawDescGZIP(), []int{5}
}

func (x *GetFsStatResponse) GetFsStat() *FsStat {
	if x != nil {
		return x.FsStat
	}
	return nil
}

type DockerStat_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Active      uint64  `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Size        float32 `protobuf:"fixed32,2,opt,name=size,proto3" json:"size,omitempty"`
	Reclaimable float32 `protobuf:"fixed32,3,opt,name=reclaimable,proto3" json:"reclaimable,omitempty"`
	TotalCount  uint64  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *DockerStat_Item) Reset() {
	*x = DockerStat_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_stat_stat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DockerStat_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerStat_Item) ProtoMessage() {}

func (x *DockerStat_Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stat_stat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerStat_Item.ProtoReflect.Descriptor instead.
func (*DockerStat_Item) Descriptor() ([]byte, []int) {
	return file_proto_stat_stat_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DockerStat_Item) GetActive() uint64 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *DockerStat_Item) GetSize() float32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DockerStat_Item) GetReclaimable() float32 {
	if x != nil {
		return x.Reclaimable
	}
	return 0
}

func (x *DockerStat_Item) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_proto_stat_stat_proto protoreflect.FileDescriptor

var file_proto_stat_stat_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x2f, 0x73, 0x74, 0x61,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x74, 0x61, 0x74, 0x22, 0xdd, 0x02,
	0x0a, 0x0a, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x12, 0x2d, 0x0a, 0x06,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x0a, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x73, 0x12, 0x3a, 0x0a, 0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x74, 0x61, 0x74,
	0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x12, 0x36,
	0x0a, 0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x43, 0x61, 0x63, 0x68, 0x65, 0x1a, 0x75, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65,
	0x63, 0x6c, 0x61, 0x69, 0x6d, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0b, 0x72, 0x65, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x16, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4a, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x22, 0x46, 0x0a, 0x06, 0x46, 0x73, 0x53, 0x74, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x66, 0x72, 0x65, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x75, 0x73, 0x65, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x46, 0x73, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x46, 0x73, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x66, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x2e, 0x46, 0x73, 0x53, 0x74, 0x61,
	0x74, 0x52, 0x06, 0x66, 0x73, 0x53, 0x74, 0x61, 0x74, 0x32, 0x95, 0x01, 0x0a, 0x0b, 0x53, 0x74,
	0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x12, 0x1a, 0x2e, 0x73, 0x74, 0x61,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x46, 0x73, 0x53, 0x74, 0x61, 0x74,
	0x12, 0x16, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x73, 0x53, 0x74, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x46, 0x73, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x4b, 0x69, 0x74, 0x73, 0x75, 0x79, 0x61, 0x30, 0x38, 0x32, 0x38, 0x2f, 0x6c, 0x61, 0x62, 0x2d,
	0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2d, 0x73, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x6f, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_stat_stat_proto_rawDescOnce sync.Once
	file_proto_stat_stat_proto_rawDescData = file_proto_stat_stat_proto_rawDesc
)

func file_proto_stat_stat_proto_rawDescGZIP() []byte {
	file_proto_stat_stat_proto_rawDescOnce.Do(func() {
		file_proto_stat_stat_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_stat_stat_proto_rawDescData)
	})
	return file_proto_stat_stat_proto_rawDescData
}

var file_proto_stat_stat_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_stat_stat_proto_goTypes = []interface{}{
	(*DockerStat)(nil),            // 0: stat.DockerStat
	(*GetDockerStatRequest)(nil),  // 1: stat.GetDockerStatRequest
	(*GetDockerStatResponse)(nil), // 2: stat.GetDockerStatResponse
	(*FsStat)(nil),                // 3: stat.FsStat
	(*GetFsStatRequest)(nil),      // 4: stat.GetFsStatRequest
	(*GetFsStatResponse)(nil),     // 5: stat.GetFsStatResponse
	(*DockerStat_Item)(nil),       // 6: stat.DockerStat.Item
}
var file_proto_stat_stat_proto_depIdxs = []int32{
	6, // 0: stat.DockerStat.images:type_name -> stat.DockerStat.Item
	6, // 1: stat.DockerStat.containers:type_name -> stat.DockerStat.Item
	6, // 2: stat.DockerStat.local_volumes:type_name -> stat.DockerStat.Item
	6, // 3: stat.DockerStat.build_cache:type_name -> stat.DockerStat.Item
	0, // 4: stat.GetDockerStatResponse.docker_stat:type_name -> stat.DockerStat
	3, // 5: stat.GetFsStatResponse.fs_stat:type_name -> stat.FsStat
	1, // 6: stat.StatService.GetDockerStat:input_type -> stat.GetDockerStatRequest
	4, // 7: stat.StatService.GetFsStat:input_type -> stat.GetFsStatRequest
	2, // 8: stat.StatService.GetDockerStat:output_type -> stat.GetDockerStatResponse
	5, // 9: stat.StatService.GetFsStat:output_type -> stat.GetFsStatResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_stat_stat_proto_init() }
func file_proto_stat_stat_proto_init() {
	if File_proto_stat_stat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_stat_stat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DockerStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_stat_stat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDockerStatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_stat_stat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDockerStatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_stat_stat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_stat_stat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFsStatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_stat_stat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFsStatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_stat_stat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DockerStat_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_stat_stat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stat_stat_proto_goTypes,
		DependencyIndexes: file_proto_stat_stat_proto_depIdxs,
		MessageInfos:      file_proto_stat_stat_proto_msgTypes,
	}.Build()
	File_proto_stat_stat_proto = out.File
	file_proto_stat_stat_proto_rawDesc = nil
	file_proto_stat_stat_proto_goTypes = nil
	file_proto_stat_stat_proto_depIdxs = nil
}
